{% set name = "zeroc-ice" %}
{% set version = "3.6.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 4235ffeb605bcd4e22e716577f7d61e4aa1bc82f65276bb542701a81b7933356
  patches:
    - patch  # [not win]
    # https://github.com/glencoesoftware/zeroc-ice-py-patches/blob/ba13c76d5a6ccc4d88ea68b58c1fa86bab0da7e8/0002-python-311-support.patch
    - 0002-python-311-support.patch
    # https://github.com/glencoesoftware/zeroc-ice-py-patches/blob/ba13c76d5a6ccc4d88ea68b58c1fa86bab0da7e8/0003-python-312-support.patch
    - 0003-python-312-support.patch
    # https://github.com/glencoesoftware/zeroc-ice-py-patches/blob/ba13c76d5a6ccc4d88ea68b58c1fa86bab0da7e8/0004-visual-studio-2022-support.patch
    # Ignore the patch name, it's also required for building on OSX
    - 0004-visual-studio-2022-support.patch
    # https://github.com/glencoesoftware/zeroc-ice-py-patches/blob/047e191d222438af1b2379b7cab4d5e3e046b366/0005-python-313-support.patch
    - 0005-python-313-support.patch
    # https://github.com/glencoesoftware/zeroc-ice-py-patches/blob/047e191d222438af1b2379b7cab4d5e3e046b366/0006-mcpp-unistd.patch
    - 0006-mcpp-unistd.patch

build:
  number: 7
  entry_points:
    - slice2py=slice2py:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - bzip2
    - openssl
    - libiconv
    - setuptools
  run:
    - python
    - bzip2
    - openssl
    - libiconv

test:
  imports:
    - Glacier2
    - Ice
    - IceBox
    - IceGrid
    - IceMX
    - IcePatch2
    - IcePy
    - IceStorm
  commands:
    - slice2py --help

about:
  home: "https://zeroc.com"
  license: GPL-2.0-only
  license_family: GPL2
  license_file:
    - ICE_LICENSE
  summary: "Ice is a comprehensive RPC framework with support for Python, C++, .NET, Java, JavaScript and more."

extra:
  recipe-maintainers:
    - dpryan79
    - joshmoore
    - manics
    - psobolewskiphd
